-- ============================================
-- Malaysia Food Database - Complete Installation Script
-- Generated by: export_to_sql.py
-- Generated at: 2026-09-07 00:20:32
-- Total valid records: 35
-- Database: malaysia_food_db
-- ============================================

-- ============================================
-- 1. Create Database (If Not Exists)
-- ============================================
CREATE DATABASE IF NOT EXISTS `malaysia_food_db` 
    CHARACTER SET utf8mb4 
    COLLATE utf8mb4_unicode_ci;

USE `malaysia_food_db`;

-- ============================================
-- 2. Drop Existing Tables (if any)
-- ============================================
DROP TABLE IF EXISTS `malaysia_food`;
DROP TABLE IF EXISTS `malaysia_food_johor`;
DROP TABLE IF EXISTS `malaysia_food_melaka`;
DROP TABLE IF EXISTS `malaysia_food_kl`;

-- ============================================
-- 3. Master Table (All Data)
-- ============================================
CREATE TABLE `malaysia_food` (
    -- Primary Key,
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key ID',
,
    -- Basic Information,
    `name` VARCHAR(100) NOT NULL COMMENT 'Restaurant/Food Name',
    `cuisine` VARCHAR(50) DEFAULT NULL COMMENT 'Cuisine/Flavor Category',
    `price` VARCHAR(50) DEFAULT NULL COMMENT 'Price Range or Avg Spending',
    `rating` DECIMAL(3,2) DEFAULT NULL COMMENT 'Rating (Out of 5.0)',
    `area` VARCHAR(50) DEFAULT NULL COMMENT 'Geographic Area',
    `url` VARCHAR(500) DEFAULT NULL COMMENT 'Amap / Map Link',
    `hours` VARCHAR(200) DEFAULT NULL COMMENT 'Business Hours',
    `notes` TEXT DEFAULT NULL COMMENT 'Recommended Dishes / Notes',
,
    -- System Fields,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
,
    -- Indexes,
    PRIMARY KEY (`id`),
    INDEX `idx_name` (`name`),
    INDEX `idx_cuisine` (`cuisine`),
    INDEX `idx_rating` (`rating`),
    INDEX `idx_area` (`area`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='malaysia_food Table'

BEGIN;

INSERT INTO `malaysia_food` (`name`, `cuisine`, `price`, `rating`, `area`, `url`, `hours`, `notes`) VALUES
    ('RunningMan Korea Restaurant', 'BBQ', 'RM 40-60', '4.4', 'Johor', 'https://maps.app.goo.gl/SLcFTksQKvBHkXvy6?g_st=ic', '10:00-22:00', 'Kimchi soup'),
    ('Restoran Arab Zaatar', 'Arabic dishes', 'RM 30-80', '4.8', 'Johor', 'https://maps.app.goo.gl/H4Txq32iZoJJZ8FTA', '10:00–01:00', 'Mix Grill Family Size'),
    ('Restoran Al-Safa Iskandar Puteri', 'Mamak', 'RM 1-20', '4.2', 'Johor', 'https://maps.app.goo.gl/fbhHDxUXvKXWk2m58', '24H operation', 'Roti Kosong, Roti Telur,Megi Goreng'),
    ('阿华牛肉面 Ah Hua Beef noodles', 'Beef noodles', 'RM 20-40', '4.4', 'Johor', 'https://maps.app.goo.gl/WbV8RYg739TsiKUa6', '08:00–21:00, Wednesday, rest', 'Beef noodles, 砂锅麻油鸡'),
    ('Jonker 88', 'Dessert', 'RM 1-20', '3.8', 'Melaka', 'https://maps.app.goo.gl/35g3HyHiC8BB2uN36', '09:30–18:00', 'Jonker Street Chendol'),
    ('Da Ma Kuey Teow Sutera', 'Restaurant', 'RM 1-20', '3.9', 'Johor', 'https://maps.app.goo.gl/xmnJtSWWWocBa5LU8', '17:30–02:00', 'Kuey Teow'),
    ('McQuek''s Satay Celup', 'Satay restaurant', 'RM 20-40', '4.5', 'Melaka', 'https://maps.app.goo.gl/vM3s47EguZwixKCQ8', '16:00–23:00, Wednesday, rest', 'Satay'),
    ('BBQ Box (Mount Austin)', 'Mandarin restaurant', 'RM 40-60', '3.9', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, 'Mount Austin'),
    ('Dajia Yuen Restaurant', 'Restaurant', 'RM 20-40', '4.1', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('Meet House Cafe', 'Cafe', 'RM 20-40', '4.5', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('Shüü Cafe', 'Cafe', 'RM 20-40', '4.1', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('Heng Park Garden Cafe', 'Asian', 'RM 1-20', '3.8', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('arest Cafe Bukit Indah', 'Restaurant', 'RM 20-40', '4.9', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, 'Bukit Indah'),
    ('Der'' Cabin Bistro Gelang Patah', 'Restaurant', 'RM 20-40', '4.8', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, 'Gelang Patah'),
    ('Queen Bean House 皇后红豆冰', 'Dessert shop', NULL, '4.3', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('火岩山擂茶 Volcano Thunder Tea', 'Restaurant', 'RM 1-20', '4.4', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('Arashi Shabu-Shabu', 'Shabu Shabu', 'RM 40-120', '4.9', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('Hot Pot Shabu Shabu Bukit Indah', 'Hot Pot', 'RM 40-60', '4.6', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, 'Bukit Indah'),
    ('HAVOC Hotpot', 'Buffet', 'RM 40-60', '4.0', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('大吉利自助火锅烤肉', 'Buffet', 'RM 40-60', '4.7', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('（SinHaiCheng）', 'Restaurant', 'RM 1-40', '4.1', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('中华风味湘菜馆', 'Restaurant', 'RM 20-100', '3.9', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, 'Hunan cuisine'),
    ('Zen+ Korean BBQ(JOHOR BAHRU)', 'Korean BBQ', 'RM 40-60', '4.4', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('7773 Kopitiam', 'Coffee shop', 'RM 1-20', '2.9', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('Kopitiam Tong Nam DSY', 'Asian', 'RM 1-20', '3.9', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('Manzanita Pâtisserie & Boulangerie - Eco Botanic', 'Cafe', 'RM 20-40', '4.8', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, 'Eco Botanic'),
    ('Village Park Restaurant', 'Malaysian', 'RM 1-20', '4.3', 'KL', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('Restaurant Tau Fu', 'Chinese', 'RM 1-20', '4.5', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('一日山品 Something Bakery @ Bukit Cina', 'Cafe', 'RM 20-40', '4.4', 'Melaka', 'https://maps.app.goo.gl/DWPBnDWwiEDBwT8cA', NULL, 'Bukit Cina'),
    ('Kubu Yong Tau Foo Kopitiam', 'Chinese', 'RM 1-20', '4.5', 'Melaka', 'https://maps.app.goo.gl/DWPBnDWwiEDBwT8cA', NULL, 'Yong Tau Foo'),
    ('Nancy''s Kitchen', 'Nyonya restaurant', 'RM 20-40', '3.9', 'Melaka', 'https://maps.app.goo.gl/DWPBnDWwiEDBwT8cA', NULL, NULL),
    ('Oriental Cafe', 'Chinese Noodles', 'RM 1-20', '4.1', 'Melaka', 'https://maps.app.goo.gl/DWPBnDWwiEDBwT8cA', NULL, NULL),
    ('Restoran Kok Keong', 'Chinese', 'RM 1-20', '4.0', 'Melaka', 'https://maps.app.goo.gl/DWPBnDWwiEDBwT8cA', NULL, NULL),
    ('Restaurant Lee Swee Meng', 'Chinese', 'RM 20-40', '4.2', 'Melaka', 'https://maps.app.goo.gl/DWPBnDWwiEDBwT8cA', NULL, NULL),
    ('Restoran Thai Xiang', 'Thai', 'RM 1-20', '4.3', 'Melaka', 'https://maps.app.goo.gl/DWPBnDWwiEDBwT8cA', NULL, NULL);

COMMIT;

-- ============================================
-- 4. Area-Specific Tables
-- ============================================
-- Table for area: Johor
CREATE TABLE `malaysia_food_johor` (
    -- Primary Key,
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key ID',
,
    -- Basic Information,
    `name` VARCHAR(100) NOT NULL COMMENT 'Restaurant/Food Name',
    `cuisine` VARCHAR(50) DEFAULT NULL COMMENT 'Cuisine/Flavor Category',
    `price` VARCHAR(50) DEFAULT NULL COMMENT 'Price Range or Avg Spending',
    `rating` DECIMAL(3,2) DEFAULT NULL COMMENT 'Rating (Out of 5.0)',
    `area` VARCHAR(50) DEFAULT NULL COMMENT 'Geographic Area',
    `url` VARCHAR(500) DEFAULT NULL COMMENT 'Amap / Map Link',
    `hours` VARCHAR(200) DEFAULT NULL COMMENT 'Business Hours',
    `notes` TEXT DEFAULT NULL COMMENT 'Recommended Dishes / Notes',
,
    -- System Fields,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
,
    -- Indexes,
    PRIMARY KEY (`id`),
    INDEX `idx_name` (`name`),
    INDEX `idx_cuisine` (`cuisine`),
    INDEX `idx_rating` (`rating`),
    INDEX `idx_area` (`area`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='malaysia_food_johor Table'

BEGIN;

INSERT INTO `malaysia_food_johor` (`name`, `cuisine`, `price`, `rating`, `area`, `url`, `hours`, `notes`) VALUES
    ('RunningMan Korea Restaurant', 'BBQ', 'RM 40-60', '4.4', 'Johor', 'https://maps.app.goo.gl/SLcFTksQKvBHkXvy6?g_st=ic', '10:00-22:00', 'Kimchi soup'),
    ('Restoran Arab Zaatar', 'Arabic dishes', 'RM 30-80', '4.8', 'Johor', 'https://maps.app.goo.gl/H4Txq32iZoJJZ8FTA', '10:00–01:00', 'Mix Grill Family Size'),
    ('Restoran Al-Safa Iskandar Puteri', 'Mamak', 'RM 1-20', '4.2', 'Johor', 'https://maps.app.goo.gl/fbhHDxUXvKXWk2m58', '24H operation', 'Roti Kosong, Roti Telur,Megi Goreng'),
    ('阿华牛肉面 Ah Hua Beef noodles', 'Beef noodles', 'RM 20-40', '4.4', 'Johor', 'https://maps.app.goo.gl/WbV8RYg739TsiKUa6', '08:00–21:00, Wednesday, rest', 'Beef noodles, 砂锅麻油鸡'),
    ('Da Ma Kuey Teow Sutera', 'Restaurant', 'RM 1-20', '3.9', 'Johor', 'https://maps.app.goo.gl/xmnJtSWWWocBa5LU8', '17:30–02:00', 'Kuey Teow'),
    ('BBQ Box (Mount Austin)', 'Mandarin restaurant', 'RM 40-60', '3.9', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, 'Mount Austin'),
    ('Dajia Yuen Restaurant', 'Restaurant', 'RM 20-40', '4.1', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('Meet House Cafe', 'Cafe', 'RM 20-40', '4.5', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('Shüü Cafe', 'Cafe', 'RM 20-40', '4.1', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('Heng Park Garden Cafe', 'Asian', 'RM 1-20', '3.8', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('arest Cafe Bukit Indah', 'Restaurant', 'RM 20-40', '4.9', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, 'Bukit Indah'),
    ('Der'' Cabin Bistro Gelang Patah', 'Restaurant', 'RM 20-40', '4.8', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, 'Gelang Patah'),
    ('Queen Bean House 皇后红豆冰', 'Dessert shop', NULL, '4.3', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('火岩山擂茶 Volcano Thunder Tea', 'Restaurant', 'RM 1-20', '4.4', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('Arashi Shabu-Shabu', 'Shabu Shabu', 'RM 40-120', '4.9', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('Hot Pot Shabu Shabu Bukit Indah', 'Hot Pot', 'RM 40-60', '4.6', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, 'Bukit Indah'),
    ('HAVOC Hotpot', 'Buffet', 'RM 40-60', '4.0', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('大吉利自助火锅烤肉', 'Buffet', 'RM 40-60', '4.7', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('（SinHaiCheng）', 'Restaurant', 'RM 1-40', '4.1', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('中华风味湘菜馆', 'Restaurant', 'RM 20-100', '3.9', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, 'Hunan cuisine'),
    ('Zen+ Korean BBQ(JOHOR BAHRU)', 'Korean BBQ', 'RM 40-60', '4.4', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('7773 Kopitiam', 'Coffee shop', 'RM 1-20', '2.9', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('Kopitiam Tong Nam DSY', 'Asian', 'RM 1-20', '3.9', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL),
    ('Manzanita Pâtisserie & Boulangerie - Eco Botanic', 'Cafe', 'RM 20-40', '4.8', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, 'Eco Botanic'),
    ('Restaurant Tau Fu', 'Chinese', 'RM 1-20', '4.5', 'Johor', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL);

COMMIT;

-- Table for area: Melaka
CREATE TABLE `malaysia_food_melaka` (
    -- Primary Key,
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key ID',
,
    -- Basic Information,
    `name` VARCHAR(100) NOT NULL COMMENT 'Restaurant/Food Name',
    `cuisine` VARCHAR(50) DEFAULT NULL COMMENT 'Cuisine/Flavor Category',
    `price` VARCHAR(50) DEFAULT NULL COMMENT 'Price Range or Avg Spending',
    `rating` DECIMAL(3,2) DEFAULT NULL COMMENT 'Rating (Out of 5.0)',
    `area` VARCHAR(50) DEFAULT NULL COMMENT 'Geographic Area',
    `url` VARCHAR(500) DEFAULT NULL COMMENT 'Amap / Map Link',
    `hours` VARCHAR(200) DEFAULT NULL COMMENT 'Business Hours',
    `notes` TEXT DEFAULT NULL COMMENT 'Recommended Dishes / Notes',
,
    -- System Fields,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
,
    -- Indexes,
    PRIMARY KEY (`id`),
    INDEX `idx_name` (`name`),
    INDEX `idx_cuisine` (`cuisine`),
    INDEX `idx_rating` (`rating`),
    INDEX `idx_area` (`area`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='malaysia_food_melaka Table'

BEGIN;

INSERT INTO `malaysia_food_melaka` (`name`, `cuisine`, `price`, `rating`, `area`, `url`, `hours`, `notes`) VALUES
    ('Jonker 88', 'Dessert', 'RM 1-20', '3.8', 'Melaka', 'https://maps.app.goo.gl/35g3HyHiC8BB2uN36', '09:30–18:00', 'Jonker Street Chendol'),
    ('McQuek''s Satay Celup', 'Satay restaurant', 'RM 20-40', '4.5', 'Melaka', 'https://maps.app.goo.gl/vM3s47EguZwixKCQ8', '16:00–23:00, Wednesday, rest', 'Satay'),
    ('一日山品 Something Bakery @ Bukit Cina', 'Cafe', 'RM 20-40', '4.4', 'Melaka', 'https://maps.app.goo.gl/DWPBnDWwiEDBwT8cA', NULL, 'Bukit Cina'),
    ('Kubu Yong Tau Foo Kopitiam', 'Chinese', 'RM 1-20', '4.5', 'Melaka', 'https://maps.app.goo.gl/DWPBnDWwiEDBwT8cA', NULL, 'Yong Tau Foo'),
    ('Nancy''s Kitchen', 'Nyonya restaurant', 'RM 20-40', '3.9', 'Melaka', 'https://maps.app.goo.gl/DWPBnDWwiEDBwT8cA', NULL, NULL),
    ('Oriental Cafe', 'Chinese Noodles', 'RM 1-20', '4.1', 'Melaka', 'https://maps.app.goo.gl/DWPBnDWwiEDBwT8cA', NULL, NULL),
    ('Restoran Kok Keong', 'Chinese', 'RM 1-20', '4.0', 'Melaka', 'https://maps.app.goo.gl/DWPBnDWwiEDBwT8cA', NULL, NULL),
    ('Restaurant Lee Swee Meng', 'Chinese', 'RM 20-40', '4.2', 'Melaka', 'https://maps.app.goo.gl/DWPBnDWwiEDBwT8cA', NULL, NULL),
    ('Restoran Thai Xiang', 'Thai', 'RM 1-20', '4.3', 'Melaka', 'https://maps.app.goo.gl/DWPBnDWwiEDBwT8cA', NULL, NULL);

COMMIT;

-- Table for area: KL
CREATE TABLE `malaysia_food_kl` (
    -- Primary Key,
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key ID',
,
    -- Basic Information,
    `name` VARCHAR(100) NOT NULL COMMENT 'Restaurant/Food Name',
    `cuisine` VARCHAR(50) DEFAULT NULL COMMENT 'Cuisine/Flavor Category',
    `price` VARCHAR(50) DEFAULT NULL COMMENT 'Price Range or Avg Spending',
    `rating` DECIMAL(3,2) DEFAULT NULL COMMENT 'Rating (Out of 5.0)',
    `area` VARCHAR(50) DEFAULT NULL COMMENT 'Geographic Area',
    `url` VARCHAR(500) DEFAULT NULL COMMENT 'Amap / Map Link',
    `hours` VARCHAR(200) DEFAULT NULL COMMENT 'Business Hours',
    `notes` TEXT DEFAULT NULL COMMENT 'Recommended Dishes / Notes',
,
    -- System Fields,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
,
    -- Indexes,
    PRIMARY KEY (`id`),
    INDEX `idx_name` (`name`),
    INDEX `idx_cuisine` (`cuisine`),
    INDEX `idx_rating` (`rating`),
    INDEX `idx_area` (`area`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='malaysia_food_kl Table'

BEGIN;

INSERT INTO `malaysia_food_kl` (`name`, `cuisine`, `price`, `rating`, `area`, `url`, `hours`, `notes`) VALUES
    ('Village Park Restaurant', 'Malaysian', 'RM 1-20', '4.3', 'KL', 'https://maps.app.goo.gl/eKFCvkJushcPfcF79', NULL, NULL);

COMMIT;


-- ============================================
-- 5. Data Validation Queries (Master Table)
-- ============================================

-- Check total imported records
SELECT COUNT(*) AS total_records FROM `malaysia_food`;

-- Statistics by cuisine
SELECT 
    `cuisine`,
    COUNT(*) AS count,
    ROUND(AVG(`rating`), 2) AS avg_rating
FROM `malaysia_food`
WHERE `cuisine` IS NOT NULL
GROUP BY `cuisine`
ORDER BY count DESC;

-- High-rated recommendations (4.8+)
SELECT `name`, `cuisine`, `rating`, `price`, `notes`
FROM `malaysia_food`
WHERE `rating` >= 4.8
ORDER BY `rating` DESC;

-- Group by price range
SELECT 
    CASE 
        WHEN `price` REGEXP '^[¥RM]+[0-9]+$' THEN 'Budget'
        WHEN `price` REGEXP '^[¥RM]+[0-9]-[0-9]+$' THEN 'Mid-range'
        ELSE 'TBD'
    END AS price_range,
    COUNT(*) AS count
FROM `malaysia_food`
GROUP BY price_range
ORDER BY price_range;

-- Statistics by area
SELECT `area`, COUNT(*) AS count
FROM `malaysia_food`
WHERE `area` IS NOT NULL
GROUP BY `area`
ORDER BY count DESC;



-- ============================================
-- 6. Create Views (Master Table)
-- ============================================

-- High-rated food view
CREATE OR REPLACE VIEW `v_high_rating_food` AS
SELECT 
    `id`, `name`, `cuisine`, `price`, `rating`, `notes`, `area`
FROM `malaysia_food`
WHERE `rating` >= 4.5
ORDER BY `rating` DESC;

-- Cuisine stats view
CREATE OR REPLACE VIEW `v_cuisine_stats` AS
SELECT 
    `cuisine`,
    COUNT(*) AS total_count,
    ROUND(AVG(`rating`), 2) AS avg_rating,
    MAX(`rating`) AS max_rating,
    MIN(`rating`) AS min_rating
FROM `malaysia_food`
WHERE `cuisine` IS NOT NULL
GROUP BY `cuisine`
ORDER BY total_count DESC;



-- ============================================
-- 7. Create Stored Procedures (Master Table)
-- ============================================

DELIMITER //

-- Query by rating range
CREATE PROCEDURE `sp_get_food_by_rating`(
    IN min_rating DECIMAL(3,2),
    IN max_rating DECIMAL(3,2)
)
BEGIN
    SELECT `name`, `cuisine`, `price`, `rating`, `notes`, `area`
    FROM `malaysia_food`
    WHERE `rating` BETWEEN min_rating AND max_rating
    ORDER BY `rating` DESC;
END //

-- Query by cuisine
CREATE PROCEDURE `sp_get_food_by_cuisine`(
    IN cuisine_name VARCHAR(50)
)
BEGIN
    SELECT `name`, `price`, `rating`, `notes`, `area`
    FROM `malaysia_food`
    WHERE `cuisine` = cuisine_name
    ORDER BY `rating` DESC;
END //

-- Search food (fuzzy)
CREATE PROCEDURE `sp_search_food`(
    IN keyword VARCHAR(100)
)
BEGIN
    SELECT `name`, `cuisine`, `price`, `rating`, `notes`, `area`
    FROM `malaysia_food`
    WHERE `name` LIKE CONCAT('%', keyword, '%')
       OR `notes` LIKE CONCAT('%', keyword, '%')
    ORDER BY `rating` DESC;
END //

DELIMITER ;



-- ============================================
-- Installation Complete
-- ============================================
SELECT '✅ Malaysia Food Database Installation Completed!' AS status;
SELECT '📊 Instructions:' AS info;
SELECT '  - Master table: malaysia_food (all data)' AS tips;
SELECT '  - Area tables: `malaysia_food_johor`, `malaysia_food_melaka`, `malaysia_food_kl`' AS tips;
SELECT '  - View all data: SELECT * FROM malaysia_food;' AS tips;
SELECT '  - View top-rated: SELECT * FROM v_high_rating_food;' AS tips;
SELECT '  - Stats by cuisine: SELECT * FROM v_cuisine_stats;' AS tips;
SELECT '  - Query by rating: CALL sp_get_food_by_rating(4.5, 5.0);' AS tips;
SELECT '  - Query by cuisine: CALL sp_get_food_by_cuisine(''BBQ'');' AS tips;
SELECT '  - Search food: CALL sp_search_food(''Kimchi'');' AS tips;
